# Ready Model for Deployment

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('clean_df.csv')

,age,month,day_of_week,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,...,education_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone,poutcome_nonexistent,poutcome_success
0,56,3,1,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,0,0,0,0,0,1,1,0
1,57,3,1,1,999,0,1.1,93.994,-36.4,4.857,...,0,1,0,0,0,0,0,1,1,0
2,37,3,1,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,0,0,1,0,0,1,1,0
3,40,3,1,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,0,0,0,0,0,1,1,0
4,56,3,1,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,9,5,1,999,0,-1.1,94.767,-50.8,1.028,...,0,0,0,0,1,0,0,0,1,0
41184,46,9,5,1,999,0,-1.1,94.767,-50.8,1.028,...,0,0,0,0,0,0,0,0,1,0
41185,56,9,5,2,999,0,-1.1,94.767,-50.8,1.028,...,0,0,0,0,1,0,0,0,1,0
41186,44,9,5,1,999,0,-1.1,94.767,-50.8,1.028,...,0,0,0,0,0,0,0,0,1,0
41187,74,9,5,3,999,1,-1.1,94.767,-50.8,1.028,...,0,0,0,0,1,0,0,0,0,0

In [3]:
x = df.drop('y',axis=1).values 
y = df['y'].values

In [4]:
from sklearn.preprocessing import MinMaxScaler  
scaler = MinMaxScaler()
scaled_x = scaler.fit_transform(x)

**Train model with all data. Keep the parameter same as the last optimation**

In [5]:
from sklearn.tree import DecisionTreeClassifier

tree=DecisionTreeClassifier(max_depth = 5) 
tree.fit(scaled_x, y) 
tree.score(scaled_x,y)

0.9023259201709236

**Save the model and scaler**

In [11]:
import joblib
joblib.dump(scaler,'scaler.pkl')
joblib.dump(tree, "model.pkl")

['scaler.pkl']

In [10]:
model=joblib.load('model.pkl')
scaler=joblib.load('scaler.pkl')